apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
  namespace: application
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - image: 607026328084.dkr.ecr.us-east-1.amazonaws.com/assignment-1-app:v1.1
          name: app
          env:
            - name: DBPORT
              value: "3306"
            - name: DBHOST
              value: mysql.database.svc.cluster.local
            - name: DBUSER
              value: root
            - name: DATABASE
              value: employees
            - name: DBPWD
              value: pw
            - name: APP_COLOR
              value: blue
          ports:
            - containerPort: 8080
              protocol: TCP
